{
    "openapi": "3.0.0",
    "info":{
        "title": "backend-challenge-code",
        "description": "Documentação referente ao teste passado!",
        "contact": "gustavoAlvesVieiraDev@outlook.com"
    },
    "paths":{
        "/admin/login":{
            "post":{
                "summary": "Login do administrador",
                "description": "Rota responsavel por logar um administrador no sistema",
                "tags":["Admin"],
                "requestBody": {
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/admin"
                            },
                            "examples":{
                                "admin":{
                                    "value":{
                                        "email": "teste@teste.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "204":{
                        "description": "Retorna um token de acesso administrativo.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "token":{
                                            "type":"string"
                                        }
                                    }
                                },
                                "examples":{
                                    "admin": {
                                        "value":{
                                            "token": "XXXXXXXXXXX.XXXXXXXXXX.XXXXXXXXXX"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/product":{
            "post":{
                "summary": "Inserir produto",
                "description": "Endpoint responsável por inserir um novo produto no sistema",
                "tags":["Admin"],
                "requestBody": {
                    "description": "Recebe um objeto com as informaçoes necessárias para o cadastro de um novo produto.",
                    "content":{
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties":{
                                    "name":{
                                        "type": "string"
                                    },
                                    "active":{
                                        "type": "boolean"
                                    }
                                }
                            },
                            "examples":{
                                "admin":{
                                    "value":{
                                        "name": "Netflix",
                                        "active": true
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "x-acess-token",
                        "in": "headers",
                        "description": "Token gerado no momento do login.",
                        "required": true
                    }
                ],
                "responses":{
                    "204":{
                        "description": "Retorna o id do produto inserido.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "insetedId":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples":{
                                    "admin":{
                                        "value":{
                                            "inserteId": 1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/product ":{
            "get":{
                "summary": "Listar Produtos",
                "description": "Retorna todos os produtos cadastrados no sistema",
                "tags":["Admin"],
                "responses":{
                    "204":{
                        "description": "Retorna uma array de objetos com todos os produtos.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "name":{
                                            "type": "string"
                                        },
                                        "active":{
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples":{
                                    "admin":{
                                        "value":[
                                            {
                                                "name": "Netflix",
                                                "active": true
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "x-acess-token",
                        "in": "headers",
                        "description": "Token gerado no momento do login.",
                        "required": true
                    }
                ]
            }
        },
        "/admin/orders ":{
            "get":{
                "summary": "Listar invesitmentos de todos os clientes",
                "description": "Retorna todas os invesitmentos efetuados por clientes",
                "tags":["Admin"],
                "responses":{
                    "204":{
                        "description": "Retorna uma arrya de objetos",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "name": {
                                            "type": "string"
                                        },
                                        "cpf": {
                                            "type": "string"
                                        },
                                        "nameProduct": {
                                            "type": "string"
                                        },
                                        "valuePurchase": {
                                            "type": "number"
                                        },
                                        "qtdPurchase": {
                                            "type": "number"
                                        },
                                        "total": {
                                            "type": "number"
                                        },
                                        "date": {
                                            "type": "date"
                                        }
                                    }
                                },
                                "examples":{
                                    "admin":{
                                        "value":[
                                            {                                            
                                            "name": "Gustavo Alves Vieira",
                                            "cpf": "22202123060",
                                            "nameProduct": "Facebook",
                                            "valuePurchase": 150,
                                            "qtdPurchase": 10,
                                            "total": 1500,
                                            "date": "2022-12-01T03:00:00.000Z"
                                        }
                                    ]
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "x-acess-token",
                        "in": "headers",
                        "description": "Token gerado no momento do login.",
                        "required": true
                    }
                ]
            }
        },



        "/client/login ":{
            "post":{
                "summary": "Login do cliente",
                "description": "Realiza um busca no banco com as credencias informadas.",
                "tags":["Cliente"],
                "requestBody": {
                    "description": "Recebe um objeto com email e senha do cliente.",
                    "content":{
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties":{
                                    "email":{
                                        "type": "string"
                                    },
                                    "password":{
                                        "type": "string"
                                    }
                                }
                            },
                            "examples":{
                                "cliente":{
                                    "value":{
                                        "email": "teste@teste.com",
                                        "password": "123456" 
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "204":{
                        "description": "Retorna um token de acesso.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "token":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples":{
                                    "cliente":{
                                        "value":{
                                            "token":"XXXXXXXXXXX.XXXXXXXXXX.XXXXXXXXXX"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/account ":{
            "post":{
                "summary": "Criar conta",
                "description": "Realiza a inserção de um cliente no banco.",
                "tags":["Cliente"],
                "requestBody": {
                    "description": "Recebe um objeto como parametro de corpo.",
                    "content":{
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties":{
                                    "name":{
                                        "type": "string"
                                    },
                                    "email":{
                                        "type": "string"
                                    },
                                    "password":{
                                        "type": "string"
                                    },
                                    "cpf": {
                                        "type": "string"
                                    },
                                    "birth":{
                                        "type": "string"
                                    }
                                }
                            },
                            "examples":{
                                "cliente":{
                                    "value":{
                                        "name": "John Doe",
                                        "email": "email@real.com",
                                        "password": "123456",
                                        "cpf": "22200130120",
                                        "birth": "2003-01-23"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "204":{
                        "description": "Retorna o id inserido do cliente.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "insetedId":{
                                            "type": "number"
                                        }
                                    }
                                },
                                "examples":{
                                    "cliente":{
                                        "value":{
                                            "insertedId": 1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/product/:product/order ":{
            "post":{
                "summary": "Fazer ordem.",
                "description": "Realiza um investimento com base no ID do cliente e no ID do produto",
                "tags":["Cliente"],
                "requestBody": {
                    "description": "Recebe um objeto como parametro de corpo.",
                    "content":{
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties":{
                                    "valuePurchase":{
                                        "type": "number"
                                    },
                                    "qtdPurchase":{
                                        "type": "number"
                                    }
                                }
                            },
                            "examples":{
                                "cliente":{
                                    "value":{
                                        "valuePurchase": 150.00,
                                        "qtdPurchase": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "x-acess-token",
                        "in": "headers",
                        "description": "Token gerado no momento do login.",
                        "required": true
                    },
                    {
                        "name": "product",
                        "in": "headers",
                        "description": "ID do produto selecionado.",
                        "required": true
                    }
                ],
                "responses":{
                    "204":{
                        "description": "Retorna o id inserido da ordem de pedido.",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "insetedId":{
                                            "type": "number"
                                        }
                                    }
                                },
                                "examples":{
                                    "cliente":{
                                        "value":{
                                            "insertedId": 1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/order":{
            "get":{
                "summary": "Lista investimentos realizados pelo cliente logado.",
                "description": "Lista todos os investimentos realizados pelo cliente logado.",
                "tags":["Cliente"],
                "responses":{
                    "204":{
                        "description": "Retorna uma array de objetos com as informações do investimento",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties":{
                                        "name":{
                                            "type": "string"
                                        },
                                        "cpf": {
                                            "type": "string"
                                        },
                                        "nameProduct":{
                                            "type":"string"
                                        },
                                        "valuePurchase":{
                                            "type": "number"
                                        },
                                        "qtdPurchase":{
                                            "type": "number"
                                        },
                                        "total": {
                                            "type":"number"
                                        },
                                        "date": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples":{
                                    "cliente":{
                                        "value":{
                                            "name": "Gustavo Alves Vieira",
                                            "cpf": "222.222.222.62",
                                            "nameProduct": "Facebook",
                                            "valuePurchase": 200,
                                            "qtdPurchase": 2,
                                            "total": 400,
                                            "date": "2022-11-28T03:00:00.000Z"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "x-acess-token",
                        "in": "headers",
                        "description": "Token gerado no momento do login.",
                        "required": true
                    }
                ]
            }
        }
    },
    "components":{
        "schemas":{
            "admin":{
                "type": "object",
                "properties":{
                    "email": {
                        "type":"string"
                    },
                    "senha":{
                        "type":"string"
                    }
                }
            }
        }
    }
}